# Generated by Django 3.2.8 on 2021-12-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('changedCorrect', models.IntegerField()),
                ('changedWrong', models.IntegerField()),
            ],
        ),
    ]
