# Generated by Django 3.2.8 on 2021-12-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMonty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalanswer',
            name='changedCorrect',
        ),
        migrations.RemoveField(
            model_name='originalanswer',
            name='changedWrong',
        ),
    ]
