# Generated by Django 4.0 on 2021-12-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMonty', '0002_remove_originalanswer_changedcorrect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalanswer',
            name='switchedCorrect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalanswer',
            name='switchedWrong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
