# Generated by Django 3.2.8 on 2021-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMonty', '0002_auto_20211210_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalanswer',
            name='changedCorrect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalanswer',
            name='changedWrong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
